development:
  app_id: 10152573195482930
  secret: "744de0699a091678cb8d9b825dca7fb4"
  canvas_page_name: gaymenshealthsurvey
  callback_url: https://caribou.rit.edu:7027/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: sg1368
    public_host: caribou.rit.edu
    public_port: 7027
    local_port: 3000
    server_alive_interval: 0

production:
  app_id: 247060388791320
  secret: "bdc9ee8d3e02ed7e112c376fd8c76aea"
  canvas_page_name: gaymenshealthsurvey
  callback_url: https://caribou.rit.edu:7027/
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: sg1368
    public_host: caribou.rit.edu
    public_port: 7007
    local_port: 3000
    server_alive_interval: 0

test:
  app_id: 247060388791320
  secret: "bdc9ee8d3e02ed7e112c376fd8c76aea"
