# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20131228025916) do

  create_table "delayed_jobs", force: true do |t|
    t.integer  "priority",   default: 0, null: false
    t.integer  "attempts",   default: 0, null: false
    t.text     "handler",                null: false
    t.text     "last_error"
    t.datetime "run_at"
    t.datetime "locked_at"
    t.datetime "failed_at"
    t.string   "locked_by"
    t.string   "queue"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "delayed_jobs", ["priority", "run_at"], name: "delayed_jobs_priority"

  create_table "estimates", force: true do |t|
    t.integer  "response_id"
    t.integer  "facebook_male_friends"
    t.integer  "facebook_gay_friends"
    t.string   "accuracy"
    t.integer  "right_percentage"
    t.integer  "facebook_recruitable_friends"
    t.string   "accuracy_recruitable"
    t.integer  "right_percentage_recruitable"
    t.string   "how_recruited"
    t.string   "email_address"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "facebook_friendships", force: true do |t|
    t.integer  "lower_facebook_user_id"
    t.integer  "higher_facebook_user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "facebook_friendships", ["higher_facebook_user_id"], name: "index_facebook_friendships_on_higher_facebook_user_id"
  add_index "facebook_friendships", ["lower_facebook_user_id"], name: "index_facebook_friendships_on_lower_facebook_user_id"

  create_table "facebook_responses", force: true do |t|
    t.integer  "facebook_user_id"
    t.integer  "recruit_id"
    t.string   "recruitee_coupon"
    t.string   "recruiter_coupon"
    t.boolean  "eighteen_or_older"
    t.string   "orientation"
    t.string   "gender"
    t.integer  "facebook_male_friends"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "facebook_users", force: true do |t|
    t.integer  "so_facebook_user_id"
    t.integer  "facebook_account_number"
    t.string   "hashed_facebook_account_number"
    t.string   "gender"
    t.string   "interested_in"
    t.string   "name"
    t.string   "relationship_status"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "facebook_users", ["facebook_account_number"], name: "index_facebook_users_on_facebook_account_number"
  add_index "facebook_users", ["gender"], name: "index_facebook_users_on_gender"
  add_index "facebook_users", ["hashed_facebook_account_number"], name: "index_facebook_users_on_hashed_facebook_account_number"
  add_index "facebook_users", ["interested_in"], name: "index_facebook_users_on_interested_in"
  add_index "facebook_users", ["relationship_status"], name: "index_facebook_users_on_relationship_status"
  add_index "facebook_users", ["so_facebook_user_id"], name: "index_facebook_users_on_so_facebook_user_id"

  create_table "redssocs_survey_consents", force: true do |t|
    t.boolean  "eighteen_or_older"
    t.boolean  "read_and_understand"
    t.boolean  "dont_meet_all_criteria"
    t.string   "orientation"
    t.string   "gender"
    t.boolean  "facebook"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "responses", force: true do |t|
    t.string   "facebook_response_id"
    t.string   "recruitee_coupon"
    t.string   "recruiter_coupon"
    t.string   "email_address"
    t.integer  "age"
    t.string   "birth_sex"
    t.string   "bigFive_introverted"
    t.string   "bigFive_trust"
    t.string   "bigFive_lazy"
    t.string   "bigFive_cope"
    t.string   "bigFive_art"
    t.string   "bigFive_extraverted"
    t.string   "bigFive_flaws"
    t.string   "bigFive_tasks"
    t.string   "bigFive_tense"
    t.string   "bigFive_active"
    t.string   "martial"
    t.string   "num_children"
    t.string   "num_children_intouch"
    t.string   "parents"
    t.string   "parents_touch"
    t.string   "parents_partner"
    t.string   "parents_partner_touch"
    t.integer  "other_relatives"
    t.integer  "other_relatives_touch"
    t.integer  "close_friends"
    t.integer  "close_friends_touch"
    t.string   "religious"
    t.integer  "religious_members"
    t.string   "classes"
    t.integer  "talk_students_teachers"
    t.string   "employed"
    t.integer  "talk_work"
    t.integer  "visit_neighbors"
    t.string   "volunteer"
    t.integer  "num_volunteer"
    t.string   "social_group"
    t.string   "happy"
    t.string   "life_satisfaction_ideal"
    t.string   "life_satisfaction_conditions"
    t.string   "life_satisfaction_satisfied"
    t.string   "life_satisfaction_things"
    t.string   "life_satisfaction_change"
    t.string   "happiness_rating"
    t.string   "communal1_row1"
    t.string   "communal1_row2"
    t.string   "communal1_row3"
    t.string   "communal1_row4"
    t.string   "communal1_row5"
    t.string   "communal1_row6"
    t.string   "communal2_row1"
    t.string   "communal2_row2"
    t.string   "communal2_row3"
    t.string   "communal2_row4"
    t.string   "communal2_row5"
    t.string   "communal2_row6"
    t.string   "burden_row1"
    t.string   "burden_row2"
    t.string   "burden_row3"
    t.string   "burden_row4"
    t.string   "burden_row5"
    t.string   "burden_row6"
    t.string   "burden_row7"
    t.string   "belong_row1"
    t.string   "belong_row2"
    t.string   "belong_row3"
    t.string   "belong_row4"
    t.string   "belong_row5"
    t.string   "belong_row6"
    t.string   "belong_row7"
    t.string   "belong_row8"
    t.string   "belong_row9"
    t.string   "belong_row10"
    t.string   "belong_row11"
    t.string   "belong_row12"
    t.string   "belong_row13"
    t.string   "rahe_row1"
    t.string   "rahe_row2"
    t.string   "rahe_row3"
    t.string   "rahe_row4"
    t.string   "rahe_row5"
    t.string   "rahe_row6"
    t.string   "rahe_row7"
    t.string   "rahe_row8"
    t.string   "rahe_row9"
    t.string   "rahe_row10"
    t.string   "rahe_row11"
    t.string   "rahe_row12"
    t.string   "rahe_row13"
    t.string   "rahe_row14"
    t.string   "rahe_row15"
    t.string   "rahe_row16"
    t.string   "rahe_row17"
    t.string   "rahe_row18"
    t.string   "rahe_row19"
    t.string   "rahe_row20"
    t.string   "rahe_row21"
    t.string   "rahe_row22"
    t.string   "rahe_row23"
    t.string   "rahe_row24"
    t.string   "rahe_row25"
    t.string   "rahe_row26"
    t.string   "rahe_row27"
    t.string   "rahe_row28"
    t.string   "rahe_row29"
    t.string   "rahe_row30"
    t.string   "rahe_row31"
    t.string   "rahe_row32"
    t.string   "rahe_row33"
    t.string   "rahe_row34"
    t.string   "rahe_row35"
    t.string   "rahe_row36"
    t.string   "rahe_row37"
    t.string   "rahe_row38"
    t.string   "rahe_row39"
    t.string   "rahe_row40"
    t.string   "rahe_row41"
    t.string   "rahe_row42"
    t.string   "rahe_row43"
    t.string   "rahe_row44"
    t.string   "rahe_row45"
    t.string   "rahe_row46"
    t.string   "rahe_row47"
    t.string   "rahe_row48"
    t.string   "rahe_row49"
    t.string   "rahe_row50"
    t.string   "rahe_row51"
    t.string   "rahe_row52"
    t.string   "rahe_row53"
    t.string   "rahe_row54"
    t.string   "rahe_row55"
    t.string   "cope_b"
    t.string   "cope_c_row1"
    t.string   "cope_c_row2"
    t.string   "cope_c_row3"
    t.string   "cope_c_row4"
    t.string   "cope_c_row5"
    t.string   "cope_c_row6"
    t.string   "cope_c_row7"
    t.string   "cope_c_row8"
    t.string   "cope_c_row9"
    t.string   "cope_c_row10"
    t.string   "cope_c_row11"
    t.string   "cope_c_row12"
    t.string   "cope_c_row13"
    t.string   "cope_c_row14"
    t.string   "cope_c_row15"
    t.string   "cope_c_row16"
    t.string   "cope_c_row17"
    t.string   "cope_c_row18"
    t.string   "cope_c_row19"
    t.string   "cope_c_row20"
    t.string   "cope_c_row21"
    t.string   "cope_c_row22"
    t.string   "cope_c_row23"
    t.string   "cope_c_row24"
    t.string   "cope_c_row25"
    t.string   "cope_c_row26"
    t.string   "cope_c_row27"
    t.string   "cope_c_row28"
    t.string   "cope_c_row29"
    t.string   "cope_c_row30"
    t.string   "cope_c_row31"
    t.string   "cope_c_row32"
    t.string   "cope_c_row33"
    t.string   "cope_problems"
    t.string   "self_construal_row1"
    t.string   "self_construal_row2"
    t.string   "self_construal_row3"
    t.string   "self_construal_row4"
    t.string   "self_construal_row5"
    t.string   "self_construal_row6"
    t.string   "self_construal_row7"
    t.string   "self_construal_row8"
    t.string   "self_construal_row9"
    t.string   "self_construal_row10"
    t.string   "self_construal_row11"
    t.string   "self_construal_row12"
    t.string   "self_construal_row13"
    t.string   "self_construal_row14"
    t.string   "self_construal_row15"
    t.string   "self_construal_row16"
    t.string   "self_construal_row17"
    t.string   "self_construal_row18"
    t.string   "individualism_row1"
    t.string   "individualism_row2"
    t.string   "individualism_row3"
    t.string   "individualism_row4"
    t.string   "individualism_row5"
    t.string   "individualism_row6"
    t.string   "individualism_row7"
    t.string   "individualism_row8"
    t.string   "individualism_row9"
    t.string   "individualism_row10"
    t.string   "individualism_row11"
    t.string   "individualism_row12"
    t.string   "individualism_row13"
    t.string   "individualism_row14"
    t.string   "individualism_row15"
    t.string   "individualism_row16"
    t.string   "individualism_row17"
    t.string   "individualism_row18"
    t.string   "individualism_row19"
    t.string   "depression_row1"
    t.string   "depression_row2"
    t.string   "depression_row3"
    t.string   "depression_row4"
    t.string   "depression_row5"
    t.string   "depression_row6"
    t.string   "depression_row7"
    t.string   "depression_row8"
    t.string   "depression_row9"
    t.string   "depression_row10"
    t.string   "depression_row11"
    t.string   "depression_row12"
    t.string   "depression_row13"
    t.string   "depression_row14"
    t.string   "depression_row15"
    t.string   "depression_row16"
    t.string   "depression_row17"
    t.string   "depression_row18"
    t.string   "depression_row19"
    t.string   "depression_row20"
    t.string   "suicide_a"
    t.string   "suicide_b"
    t.string   "function_a"
    t.string   "function_b"
    t.string   "function_c"
    t.string   "trauma_a"
    t.string   "trauma_b"
    t.string   "trauma_c"
    t.string   "religios_dominations"
    t.string   "religious_a_row1"
    t.string   "religious_a_row2"
    t.string   "religious_a_row3"
    t.string   "how_religious"
    t.string   "religious_b"
    t.string   "religious_c"
    t.integer  "demographics_a"
    t.string   "demographics_b"
    t.string   "demographics_c"
    t.string   "demographics_d"
    t.string   "demographics_e"
    t.integer  "demographics_f"
    t.integer  "demographics_g"
    t.string   "demographics_i"
    t.string   "demographics_j"
    t.string   "demographics_k"
    t.string   "demographics_l"
    t.string   "demographics_m"
    t.string   "demographics_n"
    t.string   "demographics_o"
    t.string   "groupa1"
    t.string   "groupa2"
    t.string   "groupb1"
    t.string   "groupb2"
    t.boolean  "live_with1"
    t.boolean  "live_with2"
    t.boolean  "live_with3"
    t.boolean  "live_with4"
    t.boolean  "live_with5"
    t.boolean  "live_with6"
    t.boolean  "live_with7"
    t.boolean  "live_with8"
    t.boolean  "live_with9"
    t.boolean  "com1"
    t.boolean  "com2"
    t.boolean  "com3"
    t.boolean  "com4"
    t.boolean  "family1"
    t.boolean  "family2"
    t.boolean  "family3"
    t.boolean  "family4"
    t.boolean  "family5"
    t.boolean  "family6"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "sessions", force: true do |t|
    t.string   "session_id", null: false
    t.text     "data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "sessions", ["session_id"], name: "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], name: "index_sessions_on_updated_at"

end
