class CreateResponses < ActiveRecord::Migration
  def change
    create_table :responses do |t|
      t.string :facebook_response_id
      t.string :recruitee_coupon
      t.string :recruiter_coupon
      t.string :email_address
      t.integer :age
      t.string :birth_sex
      t.string :gender
      t.string  :latino
      t.boolean :namerican
      t.boolean :asian
      t.boolean :aamerican
      t.boolean :pacific
      t.boolean :eamerican
      t.string :marital_status
      t.string :num_children
      t.boolean :work_more_than_35
      t.boolean :work_less_than_35
      t.boolean :work_yes_ill
      t.boolean :work_yes_vacation
      t.boolean :work_yes_absent
      t.boolean :unemployed_looking
      t.boolean :unemployed_not_looking
      t.boolean :unemployed_disabled
      t.boolean :retired
      t.boolean :school_fulltime
      t.boolean :school_parttime
      t.boolean :school_break
      t.boolean :homemaker
      t.boolean :work_else
      t.string :highest_grade_level_completed
      t.string :income
      t.string :health_care_provider
      t.string :have_health_plan
      t.string :general_health
      t.string :how_satisfied
      t.integer :no_days
      t.integer :height_feet
      t.integer :height_inches
      t.integer :weight
      t.string :one_drink
      t.string :twelve_drinks
      t.string :drink_frequency_yearly
      t.string :drink_frequency_daily
      t.string :binge_drink_yearly
      t.string :binge_drink_quickly_yearly
      t.string :smoked_last_year
      t.string :smoked_yearly
      t.boolean :sedatives_last_year
      t.boolean :tranquilizers_last_year
      t.boolean :painkillers_last_year
      t.boolean :stimulants_last_year
      t.boolean :marijuana_last_year
      t.boolean :hallucinogens_last_year
      t.boolean :inhalents_last_year
      t.boolean :heroin_last_year
      t.boolean :drugs_other_last_year
      t.string :ever_self_harm
      t.string :ever_seriously_ill
      t.string  :violence_victim_ever
      t.string :violence_victim_parents
      t.string :violence_ever_neglected
      t.string :violence_ever_spouse
      t.string :violence_ever_other
      t.string :violence_ever_mugged
      t.string :care_swear
      t.string :care_fear
      t.string :care_harm
      t.string :sex_feelings
      t.string :sex_who
      t.string :sex_category
      t.string :discrimination_insurance
      t.string :discrimination_how_treated
      t.string :discrimination_public
      t.string :discrimination_job
      t.string :discrimination_bullied
      t.string :ever_aids
      t.string :ever_suicidal
      t.boolean :suicidal_thought
      t.boolean :suicidal_plan
      t.boolean :suicidal_note_hidden
      t.boolean :suicidal_note_open
      t.boolean :suicidal_method
      t.boolean :suicidal_attempt
      t.boolean :suicidal_medical
      t.boolean :suicidal_not_serious
      t.string  :frequency_facebook
      t.string  :frequency_twitter
      t.string  :frequency_google_plus
      t.string  :frequency_myspace
      t.string  :frequency_linkedin
      t.string  :frequency_other
      t.string  :frequency_tumblr
      t.string  :frequency_trevorspace
      t.string  :frequency_grindr
      t.string  :frequency_scruff
      t.string  :frequency_jackd
      t.string  :frequency_hornet
      t.string  :frequency_yelp
      t.string  :frequency_foursquare
      t.string  :frequency_flickr
      t.string  :frequency_youtube
      t.string  :frequency_pinterest
      t.string  :frequency_instagram
      t.timestamps
    end
  end
end
